[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "next dev -H 0.0.0.0"
  port = 3000
  framework = "nextjs"

[[plugins]]
  package = "@netlify/plugin-nextjs"
